accupass/config/routes.rb
Rails.application.routes.draw do
  root to:  'users#welcome', :as => 'welcome'
  get '/register' =>'users#register', :as => 'register'
  get '/login' => 'users#login', :as => 'login'
  post '/create_login_session' => 'users#create_login_session'
  delete "logout" => "users#logout", :as => "logout"
  get '/forget_first' => 'users#forget_first',:as => 'forget_first'
  post '/post_forget_first' => 'users#post_forget_first'
  get '/forget_second' => 'users#forget_second',:as => 'forget_second'
  post '/post_forget_second'=>'users#post_forget_second'
  get '/forget_third'=>'users#forget_third',:as => 'forget_third'
  post '/post_forget_third'=>'users#post_forget_third'
  post '/process_phone_login'=>'users#process_phone_login'
  post '/process_activities_information'=>'users#process_activities_information'
  get '/sign_up'=>'users#sign_up', :as =>'sign_up'
  get '/bid_list'=>'users#bid_list', :as =>'bid_list'
  get '/bid_detail'=>'users#bid_detail',:as=>'bid_detail'
  get '/show'=>'users#show'
  get '/price_static'=>'users#price_static',:as=>'price_static'
  post '/process_bidding_messages'=>'users#show'
  post '/process_bid_over'=>'users#process_bid_over'
  get 'add_user'=> 'admin#add_user',:as =>'add_user'
  get  'change_password'=> 'admin#change_password',:as => 'change_password'
  get  'manager_index'=> 'admin#manager_index',:as =>'manager_index'
  post '/post_change_password'=>'admin#post_change_password'
  delete '/del_user'=>'admin#del_user'

  resource :users, only: [:create]

end

accupass/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :user_name, :password, :password_confirmation, :forget_question, :forget_answer, :token
  before_create{generate_token(:token)}
  validates :user_name, :presence => true, :uniqueness => {:case_sensitive => false}
  validates :forget_question, :presence => true
  validates :forget_answer, :presence => true

  def generate_token(column)
    begin
      self[column]=SecureRandom.urlsafe_base64
    end while User.exists?(column=>self[column])
  end

  def user_params
    params.require(:user).permit(:user_name, :password, :password_confirmation, :forget_question, :forget_answer, :token)
  end

  def self.get_activity(user_name)
    User.find_by_user_name(user_name)
  end

  def self.get_users
    User.where("id > 2")
  end


end

accupass/app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:process_bid_over,:show,:process_phone_login,:process_activities_information ]
  def welcome
    if !current_user
      redirect_to :login
    end
    @page_index = params[:page] ||1
    if params[:user_name]
      @page_user = params[:user_name]
      @activities = Activity.get_activities(params[:user_name]).paginate(page: params[:page],per_page: 10)
    else
      @page_user = current_user.user_name
      @activities = Activity.get_activities(current_user.user_name).paginate(page: params[:page],per_page: 10)
    end
    if Bid.get_start_bid
      flash.now[:bidding]="true"
    elfse
      flash.now[:no_bidding]="true"
    end
    if session[:this_bid_over]
      session.delete(:this_bid_over)
    end
  end

  def show
    if session[:this_bid_over]
      @show_over = true
      @winner = session[:winner]
    end
    @bidding = Bid.get_start_bid
    if params[:bid_message]
      BidMessage.create(params[:bid_message])
      respond_to do |format|
        format.html { redirect_to :show }
      end
    end
      @sign_up_messages = SignUpMessage.get_sign_up_messages(@bidding[:activity_name],@bidding[:current_user] ).length
      messages = BidMessage.get_bid_messages( @bidding[:bid_id], @bidding[:activity_name], @bidding[:current_user])
      @bid_messages_count = messages.length
      @bid_messages = messages.last(10)
  end

  def process_bid_over
    if params[:no_winner]
      session[:this_bid_over] = true
      session.delete(:winner)
      respond_to do |format|
        format.json { render json: 'true'}
      end
    end
    if params[:winner_info]
      session[:this_bid_over] = true
      session[:winner]=params[:winner_info]
      respond_to do |format|
        format.json { render json: 'true'}
      end
    end
  end

  def register
    @user = User.new
  end

  def login
  end

  def logout
    cookies.delete(:token)
    redirect_to :login
  end

  def create_login_session
    user = User.get_activity(params[:user_name])
    if user && user.authenticate(params[:password])
      cookies.permanent[:token] = user.token
      if user.admin?
        redirect_to :manager_index
      else
        redirect_to :welcome
      end
    else
      flash[:error]="用户名不存在或密码错误"
      redirect_to :login
    end
  end

  def create
    @user = User.new(params[:user])
    if current_user && current_user.admin?
      if @user.save
        redirect_to :manager_index
      else
        render 'admin/add_user'
      end
    else
      if @user.save
        cookies.permanent[:token]=@user.token
        redirect_to :welcome
      else
        render :register
      end
    end
  end

  def forget_first
  end

  def post_forget_first
    if params[:user][:user_name]==''
      flash.now[:error] ='账号不能为空'
    end
    user = User.get_activity(params[:user][:user_name])
    if user
      session[:change_user_name]=params[:user][:user_name]
      redirect_to forget_second_path
    else
      render :forget_first
    end
  end

  def forget_second
    user =User.get_activity(session[:change_user_name])
    @forget_question = user[:forget_question]
  end

  def post_forget_second
    user =User.get_activity(session[:change_user_name])
    @forget_question = user[:forget_question]
    if params[:user][:forget_answer]==""
      flash.now[:error]="请输入答案"
      render :forget_second
    elsif params[:user][:forget_answer]!=user[:forget_answer]
      flash.now[:error]="忘记密码答案错误"
      render :forget_second
    else
      redirect_to :forget_third
    end
  end

  def forget_third
  end

  def post_forget_third
    user = User.get_activity(session[:change_user_name])
    if params[:user][:password]!=params[:user][:password_confirmation]
      flash.now[:error]='两次密码输入不一致，请重新输入'
      render :forget_third
    else
      user.password = params[:user][:password]
      user.password_confirmation = params[:user][:password_confirmation]
      if user.save
        cookies.permanent[:token] = user.token
        redirect_to :welcome
      end
    end
  end

  def process_phone_login
    user = User.get_activity(params[:user_name])
    respond_to do |format|
      if user && user.authenticate(params[:password])
        format.json { render json: "true" }
      else
        format.json { render json: 'false' }
      end
    end
  end

  def process_activities_information
    Activity.update_activities(params[:user_name],params[:activities])
    SignUpMessage.update_sign_up_messages(params[:user_name],params[:sign_up_messages])
    Bid.update_bids(params[:user_name],params[:bids])
    BidMessage.update_bid_messages(params[:user_name],params[:bid_messages])
    respond_to do |format|
      format.json { render json: 'true' }
    end
  end

  def sign_up
    @page_index = params[:page] ||1
    @sign_up_messages = SignUpMessage.where(:activity_name=>params[:activity_name],:current_user => params[:current_user]).paginate(page: params[:page],per_page: 10)
  end

  def bid_list
    @sign_up_people_count=SignUpMessage.where(:activity_name=>params[:activity_name],:current_user => params[:current_user]).length
    @page_index = params[:page] ||1
    @bids = Bid.where(:activity_name=>params[:activity_name],:current_user => params[:current_user]).paginate(page: params[:page],per_page: 10)
  end

  def bid_detail
    @page_index = params[:page] ||1
    @bid_messages = BidMessage.get_bid_messages(params[:bid_id],params[:activity_name],params[:current_user]).paginate(page: params[:page],per_page: 10)
    if Bid.get_bid(params[:bid_id],params[:activity_name],params[:current_user])[:status]=="start"
      flash.now[:bidding]="true"
    elsif BidMessage.get_winner(params[:bid_id],params[:activity_name],params[:current_user])
      @winner_info = BidMessage.get_winner_message(params[:bid_id],params[:activity_name],params[:current_user])
      flash.now[:winner]="true"
    else
      flash.now[:no_winner]="true"
    end
  end

  def price_static
    @page_index = params[:page] ||1
    @page_price_static = BidMessage.get_price_static(params[:bid_id],params[:activity_name],params[:current_user]).paginate(page: params[:page],per_page: 10)
    if Bid.get_bid(params[:bid_id],params[:activity_name],params[:current_user])[:status]=="start"
      flash.now[:bidding]="true"
    elsif BidMessage.get_winner(params[:bid_id],params[:activity_name],params[:current_user])
      @winner_info = BidMessage.get_winner_message(params[:bid_id],params[:activity_name],params[:current_user])
      flash.now[:winner]="true"
    else
      flash.now[:no_winner]="true"
    end
  end

end

accupass/app/views/users/bid_detail.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",welcome_path(:user_name => params[:current_user])
    %li
      =link_to "竞价列表",bid_list_path(:activity_name=>params[:activity_name],:current_user => params[:current_user])
    %li.active
      第
      =params[:bid_id]
      次竞价
  .winner
    -if flash.now[:bidding]
      活动正在进行中...
    -if flash.now[:winner]
      %p
        获胜者：
        =@winner_info.user_name
      %p
        出价：
        =@winner_info.price
        元
      %p
        手机号：
        =@winner_info.phone
    -if flash.now[:no_winner]
      本次竞价无人胜出
  .panel.panel-default
    %ul.nav.nav-tabs.nav-justified
      %li.active
        %a
          出价列表
      %li
        =link_to "价格统计",price_static_path(:bid_id=>params[:bid_id],:activity_name=>params[:activity_name],:current_user => params[:current_user])
    .tab-content
      .tab-pane.active
        %table.table
          %thead
            %tr
              %th
              %th 编号
              %th 姓名
              %th 价格/元
              %th 手机号
          %tbody
            -a = 1
            - @bid_messages.each do |bid_message|
              %tr
                %td
                %td
                  =(@page_index.to_i - 1)*10 + a
                  - a+=1
                %td
                  =bid_message.user_name
                %th
                  =bid_message.price
                %td
                  =bid_message.phone
  .text-right(style="margin-top:-40px" )
    = will_paginate @bid_messages, :previous_label=>'&laquo',:next_label=>'&raquo'

accupass/app/views/users/bid_list.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",welcome_path(:user_name => params[:current_user])
    %li.active 竞价列表
  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          竞价列表
          %div(style="float:right" )
            %h5
              =link_to "报名列表",sign_up_path(:activity_name=>params[:activity_name],:current_user => params[:current_user])
    %table.table
      %thead
        %tr
          %th
          %th 编号
          %th 名称
          %th
          %th 参与人数
      %tbody
        -a = 1
        - @bids.each do |bid|
          %tr
            %td
            %td
              =(@page_index.to_i - 1)*10 + a
              - a+=1
            %td
              =link_to "第" + bid.bid_id + "次竞价",bid_detail_path(:bid_id=>bid.bid_id,:activity_name=>params[:activity_name],:current_user => params[:current_user])
            %th
            %td
              =bid.people_count
              \/
              =@sign_up_people_count
  .text-right(style="margin-top:-40px" )
    = will_paginate @bids, :previous_label=>'&laquo',:next_label=>'&raquo'

accupass/app/views/users/forget_first.haml
.form
  .text-left
    %h4 重置密码
  .text-right
    =link_to "用户登录",login_path
  %br
  =form_for :user, url: '/post_forget_first' do |f|
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        账号
      =f.text_field :user_name, :class => 'form-control',:placeholder => '请输入账号名'
    %br
    - if flash[:error]
      .alert.alert-danger
        =flash.now[:error]
    %br
    =f.submit '下一步',:class => 'btn-local'

accupass/app/views/users/forget_second.haml
.form
  .text-left
    %h4 重置密码
  .text-right
    =link_to "用户登录",login_path
  %br
  =form_for :user, url: '/post_forget_second' do |f|
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        忘记密码问题
      %label.name.form-control
        =@forget_question
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        忘记密码答案
      =f.text_field :forget_answer, :class => 'form-control',:placeholder => '请输入答案'
    %br
    - if flash.now[:error]
      .alert.alert-danger
        =flash.now[:error]
    %br
    =f.submit '下一步',:class => 'btn-local'

accupass/app/views/users/forget_third.haml
.form
  .text-left
    %h4 重置密码
  .text-right
    =link_to "用户登录",login_path
  %br
  =form_for :user,url: '/post_forget_third' do |f|
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        请设置密码
      =f.password_field :password, :class => 'form-control',:placeholder => '请输入新密码'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        请确认密码
      =f.password_field :password_confirmation, :class => 'form-control',:placeholder => '请再次输入'
    %br
    - if flash.now[:error]
      .alert.alert-danger
        =flash.now[:error]
    %br
    =f.submit '确认修改',:class => 'btn-local'

accupass/app/views/users/login.haml
.form
  .text-left
    %h4 用户登陆
  .text-right
    =link_to "用户注册",register_path
  %br
  =form_tag "/create_login_session" do
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        账号
      =text_field_tag :user_name,params[:user_name], :class => 'form-control'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        密码
      =password_field_tag :password,params[:password], :class => 'form-control'
    .text-right
      =link_to "忘记密码",forget_first_path
    %br
    - if flash[:error]
      .alert.alert-danger
        =flash[:error]
    %br
    =submit_tag '登录',:class => 'btn-local'

accupass/app/views/users/price_static.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",welcome_path(:user_name => params[:current_user])
    %li
      =link_to "竞价列表",bid_list_path(:activity_name=>params[:activity_name],:current_user => params[:current_user])
    %li.active
      第
      =params[:bid_id]
      次竞价
  .winner
    -if flash.now[:bidding]
      活动正在进行中...
    -if flash.now[:winner]
      %p
        获胜者：
        =@winner_info.user_name
      %p
        出价：
        =@winner_info.price
        元
      %p
        手机号：
        =@winner_info.phone
    -if flash.now[:no_winner]
      本次竞价无人胜出
  .panel.panel-default.text-center
    %ul.nav.nav-tabs.nav-justified
      %li
        =link_to "出价列表",bid_detail_path(:bid_id=>params[:bid_id],:activity_name=>params[:activity_name],:current_user => params[:current_user])
      %li.active
        =link_to "价格统计"
    %table.table
      %thead
        %tr
          %th.text-center 价格/元
          %th.text-center 人数
      %tbody
        - @page_price_static.each do |static|
          %tr
            %td
              =static[:price]
            %td
              =static[:count]
  .text-right
    = will_paginate @page_price_static, :previous_label=>'&laquo',:next_label=>'&raquo'

accupass/app/views/users/register.haml
.form
  .text-left
    %h4 新用户注册
  .text-right
    =link_to "用户登录",login_path
  %br
  =form_for @user do |f|
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        账号
      =f.text_field :user_name, :class => 'form-control'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        请设置密码
      =f.password_field :password, :class => 'form-control'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        请确认密码
      =f.password_field :password_confirmation, :class => 'form-control'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        忘记密码问题
      =f.text_field :forget_question, :class => 'form-control'
    %br
    .input-group(style="width:100%" )
      %span.input-group-addon(style="width:25%" )
        忘记密码答案
      =f.text_field :forget_answer, :class => 'form-control'
    %br
    - if @user.errors.any?
      .alert.alert-danger
        =@user.errors.full_messages.first
    %br
    =f.submit '注册',:class => 'btn-local'

accupass/app/views/users/show.haml
#bidding_messages
  - if !@show_over
    .show
      .title
        =@bidding.activity_name
      %h2
        参与人数：
        =@bid_messages_count
        \/
        =@sign_up_messages
    .panel.panel-default(style="margin-top: 50px;" )
      %table.table
        %thead
          %tr
            %th.text-center
              姓名
            %th.text-center
              电话
        %tbody
          - @bid_messages.each do |message|
            %tr
              %th.text-center
                =message.user_name
              %th.text-center
                =message.phone
  - if @show_over
    .show
      .title
        =@bidding.activity_name
      %h2
        比赛结果
      %h3
        -if @winner
          %p
            获胜者：
            =@winner['user_name']
          %p
            出价：
            =@winner['price']
            元
          %p
            电话：
            =@winner['phone']
        - if !@winner
          竞价失败
:javascript
  setTimeout("$('#bidding_messages').load('show/#bidding_messages')",3000)

accupass/app/views/users/sign_up.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",welcome_path(:user_name => params[:current_user])
    %li.active 报名列表
  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          报名列表
          %div(style="float:right" )
            %h5
              =link_to "竞价列表",bid_list_path(:activity_name=>params[:activity_name],:current_user => params[:current_user])
    %table.table
      %thead
        %tr
          %th
          %th 编号
          %th 姓名
          %th
          %th 手机号
      %tbody
        -a = 1
        - @sign_up_messages.each do |message|
          %tr
            %td
            %td
              =(@page_index.to_i - 1)*10 + a
              - a+=1
            %td
              =message.user_name
            %th
            %td
              =message.phone
  .text-right(style="margin-top:-40px" )
    = will_paginate @sign_up_messages, :previous_label=>'&laquo',:next_label=>'&raquo'

accupass/app/views/users/welcome.haml
=render "shared/header"
.body
  .panel.panel-default
    .panel-heading
      .panel-title
        %h4
          活动信息
          %button.btn.btn-default(style="margin-top: -10px;float:right" )
            - if flash.now[:bidding]
              =link_to "同步展示",show_path
            -if flash.now[:no_bidding]
              =link_to "同步展示"
    %table.table
      %thead
        %tr
          %th
          %th 编号
          %th 活动名称
          %th 报名人数
          %th 竞价次数
      %tbody
        -a = 1
        - @activities.each do |activity|
          %tr
            %td
            %td
              =(@page_index.to_i - 1)*10 + a
              - a+=1
            %td
              =link_to activity.activity_name,bid_list_path(:activity_name =>activity.activity_name,:current_user=>@page_user)
            %th
              =link_to activity.sign_up_counts,sign_up_path(:activity_name =>activity.activity_name,:current_user=>@page_user)
            %td
              =link_to activity.bid_counts,bid_list_path(:activity_name =>activity.activity_name,:current_user=>@page_user)
  .text-right(style="margin-top:-40px" )
    = will_paginate @activities, :previous_label=>'&laquo',:next_label=>'&raquo'