accupass/config/routes.rb
Rails.application.routes.draw do
  root to:  'users#welcome', :as => 'welcome'
  get '/register' =>'users#register', :as => 'register'
  get '/login' => 'users#login', :as => 'login'
  post '/create_login_session' => 'users#create_login_session'
  delete "logout" => "users#logout", :as => "logout"
  get '/forget_first' => 'users#forget_first',:as => 'forget_first'
  post '/post_forget_first' => 'users#post_forget_first'
  get '/forget_second' => 'users#forget_second',:as => 'forget_second'
  post '/post_forget_second'=>'users#post_forget_second'
  get '/forget_third'=>'users#forget_third',:as => 'forget_third'
  post '/post_forget_third'=>'users#post_forget_third'
  post '/process_phone_login'=>'users#process_phone_login'
  post '/process_activities_information'=>'users#process_activities_information'
  get '/sign_up'=>'users#sign_up', :as =>'sign_up'
  get '/bid_list'=>'users#bid_list', :as =>'bid_list'
  get '/bid_detail'=>'users#bid_detail',:as=>'bid_detail'
  get '/show'=>'users#show'
  get '/price_static'=>'users#price_static',:as=>'price_static'
  post '/process_bidding_messages'=>'users#show'
  post '/process_bid_over'=>'users#process_bid_over'
  get 'add_user'=> 'admin#add_user',:as =>'add_user'
  get  'change_password'=> 'admin#change_password',:as => 'change_password'
  get  'manager_index'=> 'admin#manager_index',:as =>'manager_index'
  post '/post_change_password'=>'admin#post_change_password'
  delete '/del_user'=>'admin#del_user'

  resource :users, only: [:create]

end

accupass/app/views/admin/add_user.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",manager_index_path
    %li.active 添加用户
  .form
    %br
    =form_for @user do |f|
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          账号
        =f.text_field :user_name, :class => 'form-control'
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          请设置密码
        =f.password_field :password, :class => 'form-control'
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          请确认密码
        =f.password_field :password_confirmation, :class => 'form-control'
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          忘记密码问题
        =f.text_field :forget_question, :class => 'form-control'
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          忘记密码答案
        =f.text_field :forget_answer, :class => 'form-control'
      %br
      - if @user.errors.any?
        .alert.alert-danger
          =@user.errors.full_messages.first
      %br
      =f.submit '确认添加',:class => 'btn-local'

accupass/app/views/admin/change_password.haml
=render "shared/header"
.body
  %ol.breadcrumb
    %li
      =link_to "首页",manager_index_path
    %li.active 修改用户密码
  .form
    %br
    =form_for :user,url: '/post_change_password' do |f|
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          账号
        =f.label :user_name,params[:user_name], :class => 'name form-control '
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          请设置密码
        =f.password_field :password, :class => 'form-control',:placeholder => '请输入新密码'
      %br
      .input-group(style="width:100%" )
        %span.input-group-addon(style="width:25%" )
          请确认密码
        =f.password_field :password_confirmation, :class => 'form-control',:placeholder => '请再次输入'
      %br
      - if flash[:error]
        .alert.alert-danger
          =flash[:error]
      - if flash.now[:succeed]
        .modal.fade#succeed
          .modal-dialog
            .modal-content
              .modal-header
                %button(type="button" class="close" data-dismiss="modal" aria-hidden="true") &times
                .modal-title.question_size
              .modal-body
                %div(style='text-align:center')
                  %div
                    %h4(style="font-size: 30px")
                      修改成功！
              .modal-footer
                %h4(style="font-size: 30px" )
                  %button.btn.btn-default
                    =link_to '确定',manager_index_path
        :javascript
          $('#succeed').modal('show')
      =f.submit '确认修改',:class => 'btn-local'

accupass/app/views/admin/manager_index.haml
=render "shared/header"
.body
  .panel.panel-default
    .panel-heading
      %h3.panel-title
        用户管理
        %button.btn.btn-default(style="margin-left:25px" )
          =link_to "+添加用户",add_user_path
    %table.table
      %thead
        %tr
          %th
          %th 编号
          %th 用户名
          %th
          %th 操作
      %tbody
        -a = 1
        - @users.each do |user|
          %tr
            %td
            %td
              =(@page_index.to_i - 1)*10 + a
              - a+=1
            %td
              =link_to user.user_name,welcome_path(:user_name => user.user_name)
            %th
            %td
              =link_to "删除", del_user_path(:user_name=>user[:user_name]),data: { confirm: "您确定要删除"+user[:user_name]+"？"},:method => :delete
              =link_to "修改密码",change_password_path(:user_name => user[:user_name])
  .text-right
    = will_paginate @users, :previous_label=>'&laquo',:next_label=>'&raquo'